### ISSUE TITLE
Missing validation error messages

### ISSUE THREAD

**Issue by jelhan** [jelhan/croodle#220]
Validation error messages are not shown for:

- [x] Day selection on `/create/options` for "I want to find a date" (#257)
- [x] Option input fields on `/create/options` for "I want to answer a question" (#262)
- [x] Time input fields on `/create/options-datetime` (#262)
- [ ] Answer selection for participation on `/poll/:id/participation`

Calendar for day selection and radio buttons for answer selection in participation does not even indicate the error state.

**Comment by jelhan** [comment]
>  Option input fields on /create/options for "I want to answer a question"

This is blocked by https://github.com/kaliber5/ember-bootstrap/issues/917.

**Comment by jelhan** [comment]
> * Answer selection for participation on `/poll/:id/participation`

Is already fixed. Not quite sure why. I guess it was also fixed by #262.
